COULEUR_PRIMAIRE = '#6366f1'
COULEUR_SECONDAIRE = '#334155'
COULEUR_FOND = '#0f172a'
COULEUR_TEXTE = '#f8fafc'
COULEUR_ACCENT = '#10b981'
COULEUR_ATTENTION = '#f43f5e'

PION_FONT = ('Helvetica Rounded', 28, 'bold')
PION_SIZE = 1
PION_WIDTH = 4
PION_BORDER_WIDTH = 0
PION_RELIEF = 'flat'
LABEL_FONT = ('Segoe UI', 18, 'bold')
TAILLE_PLATEAU = 5
